# Generated by Django 3.2.18 on 2023-10-12 05:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geojson', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
            ],
        ),
    ]
