# Generated by Django 3.2.18 on 2023-10-29 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp_geojson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoshp',
            name='Palika',
            field=models.CharField(choices=[('', 'Select Palika'), ('Bithadchir', 'Bithadchir'), ('Bungal', 'Bungal'), ('Chabispathivera', 'Chabispathivera'), ('Durgathali', 'Durgathali'), ('JayaPrithivi', 'JayaPrithivi'), ('Kedarseu', 'Kedarseu'), ('Khaptadchhanna', 'Khaptadchhanna'), ('Masta', 'Masta'), ('Saipal', 'Saipal'), ('Surma', 'Surma'), ('Talkot', 'Talkot'), ('Thalara', 'Thalara')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geoshp',
            name='store',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geoshp',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='geoshp',
            name='file',
            field=models.FileField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='geoshp',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geoshp',
            name='uploaded_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
