# Generated by Django 3.2.18 on 2023-10-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp_geojson', '0004_auto_20231026_0427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleGeoJSONfeature',
        ),
    ]
